In [1]:
word_list = [
    "남자 남자 남자 밥",
    "남자 남자",
    "남자 남자 남자",
    "남자 남자 남자 여자 여자",
    "남자 남자 남자 밥 밥"
]

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject


In [26]:
tf_idf = TfidfVectorizer() # tf_idf를 계산 할 객체

In [6]:
tf_idf.fit_transform(word_list) # word_list : tf_idf 계산할 문장
# tf_idf 계산

<5x2 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [7]:
vector = tf_idf.fit_transform(word_list)

In [8]:
vector

<5x2 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [9]:
vector.A

array([[1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [0.58149261, 0.81355169],
       [1.        , 0.        ]])

In [14]:
tf_idf.get_feature_names()

['남자', '여자']

In [11]:
tf_idf = TfidfVectorizer(min_df = 1)

In [12]:
vector = tf_idf.fit_transform(word_list)

In [13]:
vector.A

array([[1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [0.58149261, 0.81355169],
       [1.        , 0.        ]])

In [27]:
vector = tf_idf.fit_transform(word_list)

In [28]:
def getNoun(text):
    print("text = ", text)
    stems = text.split(" ")
    print("stems = ", stems)
    print("="*30)
    return stems

In [33]:
tf_idf = TfidfVectorizer(tokenizer=getNoun, smooth_idf=False)

In [36]:
vector = tf_idf.fit_transform(word_list)

text =  남자 남자 남자 밥
stems =  ['남자', '남자', '남자', '밥']
text =  남자 남자
stems =  ['남자', '남자']
text =  남자 남자 남자
stems =  ['남자', '남자', '남자']
text =  남자 남자 남자 여자 여자
stems =  ['남자', '남자', '남자', '여자', '여자']
text =  남자 남자 남자 밥 밥
stems =  ['남자', '남자', '남자', '밥', '밥']


In [37]:
tf_idf.fit_transform(word_list)

text =  남자 남자 남자 밥
stems =  ['남자', '남자', '남자', '밥']
text =  남자 남자
stems =  ['남자', '남자']
text =  남자 남자 남자
stems =  ['남자', '남자', '남자']
text =  남자 남자 남자 여자 여자
stems =  ['남자', '남자', '남자', '여자', '여자']
text =  남자 남자 남자 밥 밥
stems =  ['남자', '남자', '남자', '밥', '밥']


<5x3 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [39]:
tf_idf.get_feature_names()

['남자', '밥', '여자']

In [38]:
vector.A

array([[0.84274417, 0.53831428, 0.        ],
       [1.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [0.49836455, 0.        , 0.86696757],
       [0.61638324, 0.78744632, 0.        ]])